import {
  SiReact,
  SiTailwindcss,
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiPostman,
  SiGit,
  SiGithub,
  SiFigma,
  SiMongoose,
  SiDocker,
} from "react-icons/si";
import { VscVscode } from "react-icons/vsc";

export const iconMap = {
  SiReact: SiReact,
  SiTailwindcss: SiTailwindcss,
  SiHtml5: SiHtml5,
  SiCss3: SiCss3,
  SiJavascript: SiJavascript,
  SiNodedotjs: SiNodedotjs,
  SiExpress: SiExpress,
  SiMongodb: SiMongodb,
  SiPostman: SiPostman,
  SiGit: SiGit,
  SiGithub: SiGithub,
  SiFigma: SiFigma,
  SiMongoose: SiMongoose,
  SiDocker: SiDocker,
  SiVisualstudiocode: VscVscode,
};
